# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
# SITE_DOMAIN: "http://localhost:3000"
development:
  FACEBOOK_APP_ID: "2390246831244382"
  FACEBOOK_APP_SECRET: "f9dde8e5dd9a2c72ba46fac4c1bc3022"
  GOOGLE_CLIENT_ID: 109594684087-g3nm1uegulaealb6mm3o0j18l783l1jb.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: yQto-c5rCrLi2W4BTWPic9lH
