default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  localhost: localhost

development:
  <<: *default
  database: haotruongblog_development

test:
  <<: *default
  database: haotruongblog_test

production:
  <<: *default
  database: haotruongblog_production
  username: haotruongblog
  password: <%= ENV['HAOTRUONGBLOG_DATABASE_PASSWORD'] %>
